### PR TITLE
@FromModule annotation

### PR DESCRIPTION
**Pull request by namebee**

### CODE REVIEW

**Comment by dzwdz** [comment]
don't merge until we add a linter rule to enforce this

**Review by YTG1234 — APPROVED** [review]
Agreed with dzwdz

**Comment by YTG1234** [comment]
What Java linters are there? Checkstyle?

**Comment by sylv256** [comment]
Checkstyle is good.

**Comment by sylv256** [comment]
Not sure if it's a proper linter, though. I'm not really a lint person.

**Pull request merged**
