### PR TITLE
Initialize server init on both sides

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**

### CODE REVIEW

**Comment by namebee** [comment]
👍

**Comment by YTG1234** [comment]
If we replace a server init with a server start event, we can't have modules that execute code only on dedicated servers

**Comment by YTG1234** [comment]
Resolve the conflicts and I will approve

**Comment by BoogieMonster1O1** [comment]
> If we replace a server init with a server start event, we can't have modules that execute code only on dedicated servers

explain why we can’t

**Comment by hYdos** [comment]
i mean we can but i find it simpler if the common init was for servers and server init was for dedicated servers.

**Comment by BoogieMonster1O1** [comment]
> i mean we can but i find it simpler if the common init was for servers and server init was for dedicated servers.

server init doesn't give you a server :crab:

**Pull request merged**
