### PR TITLE
Linter

### PR DESCRIPTION
**Pull request by YTG1234**
I added checkstyle, with a custom checkstyle check I made for enforcing the use of `@FromModule` on Mixin methods.

For now, using `@FromModule(ProtonModule.class)` is a temporary solution until there's something else.

### CODE REVIEW

**Comment by YTG1234** [comment]
It's worth noting that the custom check was the only check I added - not any other style checks.

**Comment by YTG1234** [comment]
You can also look into the checkstyle check at [ProtonMC/proton-checkstyle-checks](https://github.com/ProtonMC/proton-checkstyle-checks/)

**Review by dzwdz — APPROVED** [review]
nice

**Review by hYdos — APPROVED** [review]

**Comment by YTG1234** [comment]
New commit on `proton-checkstyle-checks`: [9d2b5aa2249997d146d57e9b5aca3e7f319c31c0](https://github.com/ProtonMC/proton-checkstyle-checks/commit/9d2b5aa2249997d146d57e9b5aca3e7f319c31c0)

**Review by namebee — APPROVED** [review]
Looks decent, Annoying checkstyle needs to be in a different jar though.

**Comment by YTG1234** [comment]
If you want to leave any comments, do it *now* because I'm merging in 5 minutes

**Pull request merged**
