### PR TITLE
Added stained planks.

### PR DESCRIPTION
**Pull request by mounderfod**
Added Stained Planks

### CODE REVIEW

**Comment by dzwdz** [comment]
image
i'm scared

**Review by hYdos — APPROVED** [review]

**Review by YTG1234 — APPROVED** [review]
This seems good. Maybe some work needs to be done on the textures, but it's good.

**Comment by mounderfod** [comment]
> image
> i'm scared

That's JSON for you :tiny_potato:

**Comment by YTG1234** [comment]
> Maybe some work needs to be done on the textures

Says the one who made the `compressed_diamond_block` texture

**Comment by mounderfod** [comment]
> This seems good. Maybe some work needs to be done on the textures, but it's good.

Textures are straight from Quark, I can always modify if needed.

**Review by dzwdz — APPROVED** [review]

**Pull request merged**
